# Generated by Django 4.2.1 on 2023-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255, verbose_name='Display Occupation')),
                ('country', models.CharField(max_length=255)),
                ('banner_text', models.CharField(max_length=255, verbose_name='Banner Text')),
                ('resume_link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('twitter_link', models.URLField(verbose_name='Twitter Link')),
                ('github_link', models.URLField(verbose_name='Github Link')),
                ('linkedin_link', models.URLField(verbose_name='LinkedIn Link')),
            ],
        ),
    ]
