# Generated by Django 4.2.1 on 2023-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_personaldata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='image_link',
            field=models.URLField(default='', verbose_name='Image Link'),
        ),
    ]
