# Generated by Django 4.2.1 on 2023-05-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image_link', models.URLField()),
                ('description', models.TextField()),
                ('project_link', models.URLField()),
                ('is_archived', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, limit_choices_to={'id__lte': 3}, to='app.tag')),
            ],
        ),
    ]
