# Generated by Django 4.2.1 on 2023-05-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
