# Generated by Django 4.2.1 on 2023-05-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_project_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image_link', models.URLField()),
                ('description', models.TextField()),
                ('project_link', models.URLField()),
                ('tags', models.CharField(help_text='Separate tags with "," and First 3 tag will be considered ', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
